name = "jsonhero-io"
type = "javascript"
compatibility_date = "2022-02-01"
account_id = "adad29e4f868768636890dc93d28e0e3"
workers_dev = true

kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "0ce764a472ae472bb8d2961b6d485dd5" }
]

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-dev"


[site]
bucket = "./public"
entry-point = "./dist/worker.js"

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[env.production]
route = "jsonhero.io/*"
zone_id = "af3c12add61e94b88b3d2cbfb6f65782"
kv_namespaces = [
  { binding = "DOCUMENTS", id = "0ce764a472ae472bb8d2961b6d485dd5" }
]

[env.production.vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"
SESSION_SECRET = "abc123"

# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [APIHERO_PROJECT_KEY]
